/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::VCO2_V4<1>, project::VCO2_V4<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::VCO1_V4<1>, project::VCO1_V4<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::VCF_V2<1>, project::VCF_V2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::noise_V2<1>, project::noise_V2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::DspNetwork_filo2<1>, project::DspNetwork_filo2<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::DspNetwork_filo2_vcf<1>, project::DspNetwork_filo2_vcf<NUM_POLYPHONIC_VOICES>>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


