/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "noise_V2.h"
#include "VCF_V2.h"
#include "VCO1_V4.h"
#include "VCO2_V4.h"

// Include compiled network files ------------------

#include "DspNetwork_filo2.h"
#include "DspNetwork_filo2_vcf.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

