/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::greyhole_reverb<1>, project::greyhole_reverb<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::DspNetwork_grayhole<1>, wrap::illegal_poly<project::DspNetwork_grayhole<1>>>();
		registerDataNode<project::cputest_networkdata>();
		registerDataNode<project::debug1_networkdata>();
		registerDataNode<project::debug2_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::DspNetwork_networkdata>();
		registerDataNode<project::DspNetwork2_networkdata>();
		registerDataNode<project::DspNetwork4_networkdata>();
		registerDataNode<project::Granulator_networkdata>();
		registerDataNode<project::script_fx1_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

