/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "greyhole_reverb.h"

// Include compiled network files ------------------

#include "cputest_networkdata.h"
#include "debug1_networkdata.h"
#include "debug2_networkdata.h"
#include "DspNetwork2_networkdata.h"
#include "DspNetwork4_networkdata.h"
#include "DspNetwork_grayhole.h"
#include "DspNetwork_networkdata.h"
#include "Granulator_networkdata.h"
#include "script_fx1_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

