/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "granulator_gap.h"
#include "haas_width.h"
#include "live_capture.h"
#include "oneshot_player.h"
#include "onset_player.h"
#include "stereo_spread.h"

// Include compiled network files ------------------

#include "capture_DspNetwork_networkdata.h"
#include "cinescapes_DspNetwork_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

