/** Autogenerated Main.cpp. */

// =================================| Include only the DSP files  |=================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ===========================| Now we can add the rest of the codebase |===========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =======================================| Project Factory |=======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations ----------------------------------------------------------------------
		
		registerPolyNode<project::stereo_spread<1>, project::stereo_spread<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::onset_player<1>, project::onset_player<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::oneshot_player<1>, project::oneshot_player<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::haas_width<1>, project::haas_width<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::granulator_gap<1>, project::granulator_gap<NUM_POLYPHONIC_VOICES>>();
		registerDataNode<project::capture_DspNetwork_networkdata>();
		registerDataNode<project::cinescapes_DspNetwork_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


